# Generated by Django 2.1.4 on 2019-01-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('is_company', models.BooleanField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Client')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('board_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='orders.Order')),
            ],
            options={
                'db_table': 'order_record',
            },
        ),
        migrations.CreateModel(
            name='SendedBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_boards', to='boards.Board')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'sended_board',
            },
        ),
    ]
