  version: '3'

  volumes:
    db_data_production: {}
    static_production: {}

  services:

    django-service: &django
      build:
        context: .
        dockerfile: compose/production/backend/Dockerfile
      env_file:
        - .envs/production/django.env
        - .envs/production/postgres.env
      command: bash /manage/build.sh
      volumes:
        - static_production:/static
      depends_on:
        - db
        - redis

    django-app:
      <<: *django
      command: bash /manage/run.sh
      depends_on:
        - db
        - redis
        - django-service

    django-celery:
      <<: *django
      command: celery -A alternative_backend worker -l info
      depends_on:
        - db
        - redis
        - django-service
        - django-app

    django-celery-beat:
      <<: *django
      command: celery -A alternative_backend beat -l info --pidfile=
      depends_on:
        - db
        - redis
        - django-service
        - django-app

    db:
      image: postgres:latest
      volumes:
        - db_data_production:/var/lib/postgresql/data
      env_file:
        - .envs/production/postgres.env

    redis:
      build:
        context: .
        dockerfile: compose/production/redis/Dockerfile
      command: redis-server /config/redis.conf
      depends_on:
        - db
      sysctls:
        net.core.somaxconn: '511'

    nginx:
      build:
        context: .
        dockerfile: compose/production/nginx/Dockerfile
      volumes:
        - static_production:/var/local/alternative_backend/static
      ports:
        - 80:80
      depends_on:
        - django-app
