  version: '3'  

  volumes:
    db_data: {}
    static: {}

  services:

    django-service: &django
      build:
        context: .
        dockerfile: compose/backend/Dockerfile
      env_file:
        - .envs/django.env
        - .envs/postgres.env
      command: bash /manage/build.sh
      volumes:
        - ./alternative_backend:/app
        - static:/static
      depends_on:
        - db

    django-app:
      <<: *django
      command: bash /manage/run.sh
      depends_on:
        - db
        - django-service

    db:
      image: postgres:latest
      volumes:
        - db_data:/var/lib/postgresql/data
      env_file:
        - .envs/postgres.env

    nginx:
      build: 
        context: .
        dockerfile: compose/nginx/Dockerfile
      volumes:
        - static:/var/local/alternative_backend/static
      ports:
        - 80:80
      depends_on:
        - django-app


