  version: '3'

  volumes:
    db_data_development: {}
    static_development: {}

  services:

    django-service: &django
      build:
        context: .
        dockerfile: compose/development/backend/Dockerfile
      environment:
        - SETTINGS_PATH=settings.development
        - SECRET_KEY=ox3fv+&j(rl@4*_k5_nddjs3#4@+#-y-el)m&2!c7nz0@h-34h
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=not_very_secret_password
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - PYTHONUNBUFFERED=1
      command: bash /manage/build.sh
      volumes:
        - ./alternative_backend:/app
        - static_development:/static
      depends_on:
        - db
        - redis

    django-app:
      <<: *django
      command: bash /manage/run.sh
      ports:
      - "80:9000"
      depends_on:
        - db
        - redis
        - django-service

    django-celery:
      <<: *django
      command: celery -A alternative_backend worker -l debug
      depends_on:
        - db
        - redis
        - django-app
        - django-service

    django-celery-beat:
      <<: *django
      command: celery -A alternative_backend beat -l debug --pidfile=
      depends_on:
        - db
        - redis
        - django-app
        - django-service

    db:
      image: postgres:latest
      volumes:
        - db_data_development:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=not_very_secret_password
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432

    redis:
      build:
        context: .
        dockerfile: compose/development/redis/Dockerfile
      command: sh -c "redis-server /config/redis.conf && redis-cli flushall"
      depends_on:
        - db
      sysctls:
        net.core.somaxconn: '511'
