  version: '3'

  volumes:
    db_data_development: {}
    static_development: {}

  services:

    django-service: &django
      build:
        context: .
        dockerfile: compose/development/backend/Dockerfile
      env_file:
        - .envs/development/django.env
        - .envs/development/postgres.env
      command: bash /manage/build.sh
      volumes:
        - ./alternative_backend:/app
        - static_development:/static
      depends_on:
        - db
        - redis

    django-app:
      <<: *django
      command: bash /manage/run.sh
      ports:
      - "80:80"
      depends_on:
        - db
        - redis
        - django-service

    django-celery:
      <<: *django
      command: celery -A alternative_backend worker -l debug
      depends_on:
        - db
        - redis
        - django-app
        - django-service

    django-celery-beat:
      <<: *django
      command: celery -A alternative_backend beat -l debug --pidfile=
      depends_on:
        - db
        - redis
        - django-app
        - django-service

    db:
      image: postgres:latest
      volumes:
        - db_data_development:/var/lib/postgresql/data
      env_file:
        - .envs/development/postgres.env

    redis:
      build:
        context: .
        dockerfile: compose/development/redis/Dockerfile
      command: sh -c "redis-server /config/redis.conf && redis-cli flushall"
      depends_on:
        - db
      sysctls:
        net.core.somaxconn: '511'
