# Generated by Django 2.2.6 on 2019-10-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='mold',
        ),
        migrations.AlterField(
            model_name='moldhistory',
            name='finished',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_finished', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='press',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name='moldhistory',
            table='mold_history',
        ),
        migrations.AlterModelTable(
            name='press',
            table='press',
        ),
    ]
