# Generated by Django 2.1.5 on 2019-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presses', '0002_press_press_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='press_time',
            field=models.IntegerField(),
        ),
    ]
