# Generated by Django 2.2.6 on 2019-11-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('m2', 'm2'), ('l', 'l'), ('pcs', 'pcs')], max_length=50)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'material_category',
            },
        ),
        migrations.CreateModel(
            name='MaterialPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency')),
                ('finished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_material_price_finished', to='events.Event')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_material', to='materials.Material')),
                ('started', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_material_price_started', to='events.Event')),
            ],
            options={
                'db_table': 'material_price_history',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialCategory'),
        ),
        migrations.AddField(
            model_name='material',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
    ]
