# Generated by Django 2.2.6 on 2019-10-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
