# Generated by Django 2.1.4 on 2019-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerscan',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
