# Generated by Django 2.1.5 on 2019-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='barcode',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
