# Generated by Django 2.2.6 on 2019-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
