# Generated by Django 2.1.4 on 2019-01-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerscan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerscan',
            old_name='worker',
            new_name='worker_barcode',
        ),
    ]
