# Generated by Django 2.1.4 on 2019-01-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerscan_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerscan',
            name='day_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
