# Generated by Django 2.1.4 on 2019-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20190113_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerscan',
            name='seconds',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
