# Generated by Django 2.1.4 on 2018-12-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.BigIntegerField()),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='BoardCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=200)),
                ('company_code', models.IntegerField()),
            ],
            options={
                'db_table': 'board_company',
            },
        ),
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('code', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany')),
            ],
            options={
                'db_table': 'board_model',
            },
        ),
        migrations.CreateModel(
            name='BoardScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('barcode_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Worker')),
            ],
            options={
                'db_table': 'board_scan',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany'),
        ),
        migrations.AddField(
            model_name='board',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModel'),
        ),
    ]
