# Generated by Django 2.1.4 on 2018-12-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardscan',
            old_name='barcode',
            new_name='board',
        ),
    ]
