# Generated by Django 2.1.15 on 2019-12-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('workers', '0001_initial'),
        ('boards', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='bottom_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_bottom_materials', to='materials.Material'),
        ),
        migrations.AddField(
            model_name='layout',
            name='top_graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_top_graphics', to='boards.BoardGraphic'),
        ),
        migrations.AddField(
            model_name='layout',
            name='top_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_top_materials', to='materials.Material'),
        ),
        migrations.AddField(
            model_name='boardscan',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
        migrations.AddField(
            model_name='boardscan',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
        migrations.AddField(
            model_name='boardscan',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Worker'),
        ),
        migrations.AddField(
            model_name='boardmodelmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material'),
        ),
        migrations.AddField(
            model_name='boardmodelmaterial',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='boards.BoardModel'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Layout'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='materials',
            field=models.ManyToManyField(through='boards.BoardModelMaterial', to='materials.Material', verbose_name='model_materials'),
        ),
        migrations.AddField(
            model_name='board',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany'),
        ),
        migrations.AddField(
            model_name='board',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Layout'),
        ),
        migrations.AddField(
            model_name='board',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModel'),
        ),
    ]
