# Generated by Django 2.1.5 on 2019-05-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='press_time',
            field=models.IntegerField(default=0),
        ),
    ]
