# Generated by Django 2.2.6 on 2019-11-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('workers', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardscan',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Worker'),
        ),
        migrations.AddField(
            model_name='boardmodelmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material'),
        ),
        migrations.AddField(
            model_name='boardmodelmaterial',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='boards.BoardModel'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='materials',
            field=models.ManyToManyField(through='boards.BoardModelMaterial', to='materials.Material', verbose_name='model_materials'),
        ),
        migrations.AddField(
            model_name='board',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardCompany'),
        ),
        migrations.AddField(
            model_name='board',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModel'),
        ),
    ]
