# Generated by Django 2.2.5 on 2019-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcompany',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
