# Generated by Django 2.1.15 on 2020-03-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('boards', '0002_auto_20191224_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardmodelmaterial',
            unique_together={('model', 'material')},
        ),
    ]
