# Generated by Django 2.1.4 on 2018-12-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20181222_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardscan',
            old_name='board',
            new_name='scan',
        ),
    ]
