# Generated by Django 2.1.5 on 2019-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_press_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardscan',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
