# Generated by Django 2.1.4 on 2018-12-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20181222_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardscan',
            old_name='scan',
            new_name='barcode_scan',
        ),
    ]
