# Generated by Django 2.1.4 on 2019-12-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20191205_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='default_bottom_graphic',
            new_name='bottom_graphic',
        ),
        migrations.RenameField(
            model_name='boardmodel',
            old_name='default_top_graphic',
            new_name='top_graphic',
        ),
        migrations.RemoveField(
            model_name='board',
            name='graphic_bottom',
        ),
        migrations.RemoveField(
            model_name='board',
            name='graphic_top',
        ),
        migrations.AddField(
            model_name='board',
            name='bottom_graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_graphics', to='boards.BoardGraphic'),
        ),
        migrations.AddField(
            model_name='board',
            name='top_graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_graphics', to='boards.BoardGraphic'),
        ),
        migrations.AddField(
            model_name='boardgraphic',
            name='artist',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
