# Generated by Django 2.1.4 on 2019-12-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('boards', '0004_auto_20191205_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModelLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_graphic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_bottom_graphics', to='boards.BoardGraphic')),
                ('bottom_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_bottom_materials', to='materials.Material')),
            ],
            options={
                'db_table': 'board_model_layout',
            },
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='bottom_graphic',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='top_graphic',
        ),
        migrations.AddField(
            model_name='boardmodellayout',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModel'),
        ),
        migrations.AddField(
            model_name='boardmodellayout',
            name='top_graphic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_top_graphics', to='boards.BoardGraphic'),
        ),
        migrations.AddField(
            model_name='boardmodellayout',
            name='top_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_top_materials', to='materials.Material'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModelLayout'),
        ),
    ]
