# Generated by Django 2.1.4 on 2019-12-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20191208_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='bottom_graphic',
        ),
        migrations.RemoveField(
            model_name='board',
            name='top_graphic',
        ),
        migrations.RemoveField(
            model_name='boardmodellayout',
            name='model',
        ),
        migrations.AddField(
            model_name='board',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.BoardModelLayout'),
        ),
    ]
